//
// Generated file, do not edit! Created by opp_msgtool 6.0 from CQIMessage.msg.
//

#ifndef __OPPORTUNISTICCELLULARNETWORK_CQIMESSAGE_M_H
#define __OPPORTUNISTICCELLULARNETWORK_CQIMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace opportunisticcellularnetwork {

class CQIMessage;

}  // namespace opportunisticcellularnetwork


namespace opportunisticcellularnetwork {

/**
 * Class generated from <tt>CQIMessage.msg:4</tt> by opp_msgtool.
 * <pre>
 * message CQIMessage
 * {
 *     int id;
 *     int CQI;
 * }
 * </pre>
 */
class CQIMessage : public ::omnetpp::cMessage
{
  protected:
    int id = 0;
    int CQI = 0;

  private:
    void copy(const CQIMessage& other);

  protected:
    bool operator==(const CQIMessage&) = delete;

  public:
    CQIMessage(const char *name=nullptr, short kind=0);
    CQIMessage(const CQIMessage& other);
    virtual ~CQIMessage();
    CQIMessage& operator=(const CQIMessage& other);
    virtual CQIMessage *dup() const override {return new CQIMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getId() const;
    virtual void setId(int id);

    virtual int getCQI() const;
    virtual void setCQI(int CQI);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CQIMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CQIMessage& obj) {obj.parsimUnpack(b);}


}  // namespace opportunisticcellularnetwork


namespace omnetpp {

template<> inline opportunisticcellularnetwork::CQIMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<opportunisticcellularnetwork::CQIMessage*>(ptr.get<cObject>()); }

};  // namespace omnetpp

#endif // ifndef __OPPORTUNISTICCELLULARNETWORK_CQIMESSAGE_M_H

